image:
    repository: 690641653744.dkr.ecr.ap-northeast-2.amazonaws.com/haenet-frontend
    tag: "sha-740c79ba88593f8e89bb1196b2fe4b5edf93ba37"
    pullPolicy: IfNotPresent

ingress:
    enabled: true
    className: alb
    host: foodray.net
    path: /
    pathType: Prefix
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:690641653744:certificate/4114d219-b52b-4b56-921b-b2067fd1a3c0
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/group.name: foodray
        alb.ingress.kubernetes.io/load-balancer-name: foodray-alb
        alb.ingress.kubernetes.io/healthcheck-path: /
