image:
    repository: 690641653744.dkr.ecr.ap-northeast-2.amazonaws.com/haenet-worker-gpu
    tag: "sha-59b7a02e923253acef1103a36101e0924cc35787"
    pullPolicy: IfNotPresent

env:
    APP_ENV: prod

queue:
    type: redis
    redisUrl: redis://redis-prod-master.app-prod.svc.cluster.local:6379/0
    name: "cicdex:jobs:menu_assistant"
    processingName: "cicdex:jobs:menu_assistant:processing"
config:
    LOG_LEVEL: INFO
    S3_BUCKET: haenet-s3-project
    S3_PREFIX: upload/
    S3_PREFIX_TMP: tmp
    S3_PREFIX_PERM: perm
    S3_REGION: ap-northeast-2
    MENU_ASSISTANT_RUNS_ROOT: /tmp/ai_runs
    MENU_ASSISTANT_CHROMA_S3_PREFIX: s3://haenet-s3-project/ai/chroma/
    MENU_ASSISTANT_MENU_INDEX_S3_URI: s3://haenet-s3-project/ai/json/menu_seed_with_alg_tags_variants_v3.json

secrets:
    enabled: false
    GEMINI_API_KEY: PROD_GEMINI_API_KEY_CHANGE_ME
    DB_PASSWORD: PROD_DB_PASSWORD_CHANGE_ME
    JWT_SECRET_KEY: PROD_JWT_CHANGE_ME

autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
