image:
    repository: 690641653744.dkr.ecr.ap-northeast-2.amazonaws.com/haenet-worker-gpu
    tag: "sha-f38f6bf35b4322e59470494582306c6b3a7a3aa9"
    pullPolicy: IfNotPresent

worker:
    args: ["-m", "AI.journal.worker.worker_app.main"]

env:
    APP_ENV: prod
    DB_HOST: heanet-rds-db.chm8ecgk8z74.ap-northeast-2.rds.amazonaws.com
    DB_PORT: "3306"
    DB_NAME: foodray_db_rds
    DB_USER: admin

queue:
    type: redis
    redisUrl: redis://redis-prod-master.app-prod.svc.cluster.local:6379/0
    name: "cicdex:jobs:journal"
    processingName: "cicdex:jobs:journal:processing"
config:
    LOG_LEVEL: INFO
    S3_BUCKET: haenet-s3-project
    S3_PREFIX: upload/
    S3_PREFIX_TMP: tmp
    S3_PREFIX_PERM: perm
    S3_REGION: ap-northeast-2

secrets:
    enabled: false
    GEMINI_API_KEY: PROD_GEMINI_API_KEY_CHANGE_ME
    DB_PASSWORD: PROD_DB_PASSWORD_CHANGE_ME
    JWT_SECRET_KEY: PROD_JWT_CHANGE_ME

autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
