replicaCount: 1

serviceAccount:
  create: true
  name: ""
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80


image:
  repository: 690641653744.dkr.ecr.ap-northeast-2.amazonaws.com/haenet-frontend
  tag: dev-001
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

containerPort: 80

ingress:
  enabled: false
  className: nginx
  host: app.local
  path: /
  pathType: Prefix
  annotations: {}

httpRoute:
  enabled: false


resources: {}
