image:
  repository: 690641653744.dkr.ecr.ap-northeast-2.amazonaws.com/redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

service:
  port: 6379

persistence:
  enabled: false
  size: 1Gi
  storageClassName: ""

resources: {}
