apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-prod
  namespace: argocd
spec:
  project: app-platform

  source:
    repoURL: https://github.com/jjs0224/haenet_project
    targetRevision: development
    path: k8s/charts/api
    helm:
      valueFiles:
        - ../../env/prod/api-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: app-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


