apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
spec:
  project: app-platform

  source:
    repoURL: https://github.com/mingoo684/cicdex2.git
    targetRevision: test1
    path: k8s/charts/frontend
    helm:
      valueFiles:
        - ../../env/prod/frontend-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: app-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
