apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dev
  namespace: argocd
spec:
  project: app-platform

  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev

  sources:
    # Source 1: Redis Helm chart (Bitnami)
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 24.1.0
      helm:
        releaseName: redis-dev
        valueFiles:
          - $values/k8s/env/dev/redis-values.yaml

    # Source 2: Values from your Git repo
    - repoURL: https://github.com/jjs0224/haenet_project
      targetRevision: development
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


