apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: root-app
    namespace: argocd
spec:
    project: app-platform

    source:
        repoURL: https://github.com/jjs0224/haenet_project
        targetRevision: development
        path: k8s/argocd/apps
        directory:
            recurse: true

    destination:
        server: https://kubernetes.default.svc
        namespace: argocd

    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true


