image:
    repository: 690641653744.dkr.ecr.ap-northeast-2.amazonaws.com/haenet-frontend
    tag: prod-001
    pullPolicy: IfNotPresent

imagePullSecrets: []

ingress:
    enabled: true
    className: nginx
    host: app.local
    path: /
