apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-platform
  namespace: argocd
spec:
  description: "App-of-Apps project for app-dev/app-prod (redis/frontend/api/worker)"

  sourceRepos:
    - https://github.com/jjs0224/haenet_project
    - https://charts.bitnami.com/bitnami

  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: app-prod

  # AppProject ?�체??namespace 리소?��? ??���??�용(?�순??
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"


