apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-platform
  namespace: argocd
spec:
  description: "App-of-Apps project for app-dev/app-prod (redis/frontend/api/worker)"

  sourceRepos:
    - https://github.com/mingoo684/cicdex2.git
    - https://charts.bitnami.com/bitnami

  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: app-dev
    - server: https://kubernetes.default.svc
      namespace: app-prod

  # AppProject 자체는 namespace 리소스를 폭넓게 허용(단순화)
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
