 {{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  annotations:
    # NGINX Ingress에서 정규식 경로 사용
    nginx.ingress.kubernetes.io/use-regex: "true"
    # /api 프리픽스를 제거해서 백엔드에는 /, /health 처럼 전달
    # 예) /api/health -> /health
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "api.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
                          {{- end }}