  {{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secrets
type: Opaque
stringData:
  db_password: {{ .Values.secret.dbPassword | quote }}
  jwt_secret_key: {{ .Values.secret.jwtSecretKey | quote }}
                  {{- end }}
