  {{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secrets
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  JWT_SECRET_KEY: {{ .Values.secret.jwtSecretKey | quote }}
                  {{- end }}
